spring.application.name=Meeting room booking
spring.datasource.url=jdbc:mysql://localhost:3306/meeting_room_booking
spring.datasource.username=root
spring.datasource.password=password
spring.jpa.show-sql: true